# Generated by Django 6.0.5 on 2026-06-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер")],
                default=("user", "Пользователь"),
                max_length=100,
                verbose_name="Роль",
            ),
        ),
    ]
