# Generated by Django 6.0.5 on 2026-06-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер")],
                default="user",
                max_length=100,
                verbose_name="Роль",
            ),
        ),
    ]
