# Generated by Django 6.0.5 on 2026-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_mailingattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(
                related_name="mailings", to="core.mailingrecipient"
            ),
        ),
    ]
