# Generated by Django 6.0.5 on 2026-06-01 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_mailing_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="core.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
