# Generated by Django 6.0.5 on 2026-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_mailingattempt_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                    ("finished", "Завершена"),
                ],
                default=("created", "Создана"),
                verbose_name="Статус",
            ),
        ),
    ]
