# Generated by Django 6.0.5 on 2026-06-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_mailing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="email",
            field=models.EmailField(
                default="default@example.com",
                max_length=254,
                verbose_name="Почта получателя",
            ),
        ),
    ]
