# Generated by Django 6.0.5 on 2026-06-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_mailing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.mailingrecipient",
                verbose_name="Получатель",
            ),
            preserve_default=False,
        ),
    ]
