# Generated by Django 6.0.5 on 2026-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_mailing_author_mailingrecipient_added_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                    ("finished", "Завершена"),
                    ("disabled", "Отключена"),
                ],
                default=("created", "Создана"),
                verbose_name="Статус",
            ),
        ),
    ]
